#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Yoshitaka Hirata
#SPDX-License-Indentifier: BSD-3-Clause
import sys
import datetime

def find_anniversary(date):
    with open('anniversaries.txt', 'r') as file:
        lines = file.readlines()
        for line in lines:
            if line.startswith(date):
                return line.strip().split(',')[1]
    return "その日付は存在しないか日付の入力形式が違います。\n日付をtodayか月/日の形式で入力してください。"

def main():

    if sys.argv[1]==str("today"):
        now = datetime.datetime.now()
        date=(str(now.month)+str("/")+str(now.day))
        print(find_anniversary(date))
    
    else:
        date=sys.argv[1]
        print(find_anniversary(date))

if __name__ == "__main__":
    main()

