#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Yoshitaka Hirata
#SPDX-License-Indentifier: BSD-3-Clause
import sys

def find_anniversary(date):
    with open('anniversaries.txt', 'r') as file:
        lines = file.readlines()
        for line in lines:
            if line.startswith(date):
                return line.strip().split(',')[1]
    return "入力形式が違います。日付を月/日の形式で入力してください。"

def main():
    date = sys.argv[1]
    print(find_anniversary(date))

if __name__ == "__main__":
    main()

